export const ROLES = {
  JEFE_MANTENIMIENTO: 'JEFE_MANTENIMIENTO',
  OPERARIO_MANTENIMIENTO: 'OPERARIO_MANTENIMIENTO',
  OPERARIO_PRODUCCION: 'OPERARIO_PRODUCCION',
  SUPER_USUARIO: 'SUPER_USUARIO',
}

export const ROLES_LABEL = {
  [ROLES.JEFE_MANTENIMIENTO]: 'Coordinador MTTO',
  [ROLES.OPERARIO_MANTENIMIENTO]: 'Técnico MTTO',
  [ROLES.OPERARIO_PRODUCCION]: 'Producción',
  [ROLES.SUPER_USUARIO]: 'Super Usuario',
}

export const ROLES_LIST = Object.values(ROLES)
